### ISSUE TITLE
Automate postgres-db initialization

### ISSUE THREAD

**Issue by oseasmoran73** [januschung/job-winner#12]
## Description

As of right now, instructions on how to set up DB is found in the README. It would be nice if we can have an automated script for the following:

- Check DB exists
- If it exists, disregard
- If it does not exist, initialize automatically

**Comment by oseasmoran73** [comment]
PR recently merged handles DB on initialization. If tables need to be updated, it won't handle it properly

**Comment by januschung** [comment]
Do we want to revisit this with a new issue?

**Comment by oseasmoran73** [comment]
> Do we want to revisit this with a new issue?

Most likely. Just didnt want to it to get lost in the crack so I just made a quick comment
